const uz = {
    "nav_dashboard": "Boshqaruv paneli", "nav_favorites": "Sevimlilar", "nav_emergency": "SHOSHILINCH", "search_placeholder": "Asboblarni qidirish (masalan, GCS, BMI)...",
    "dash_title": "Klinik kalkulyatorlar katalogi", "dash_subtitle": "Toifani tanlang yoki aniq protokolni qidiring.",
    "cat_all": "Barchasi", "cat_label": "BARCHA KALKULYATORLAR",
    "hero_pill": "TIBBIYOT TALABASI TOMONIDAN • SHIFOKORLAR UCHUN YARATILGAN", "hero_title_1": "Klinik asboblar", "hero_title_2": "palata aylanmasi uchun", "hero_subtitle": "4 tilda mnemonikaga ega dalillarga asoslangan kalkulyatorlar. Tez, ishonchli va mobil qurilmalarga mos.",
    "stat_student": "Talaba tomonidan", "stat_tools": "Kalkulyatorlar", "stat_langs": "Tillar", "stat_free": "Bepul",
    "footer_about": "Biz haqimizda", "footer_contact": "Aloqa", "footer_privacy": "Maxfiylik siyosati", "footer_terms": "Foydalanish shartlari", "footer_disclaimer": "Tibbiy ogohlantirish",
    "tool_gcs_title": "Glazgo koma shkalasi (GCS)", "tool_gcs_desc": "Ong darajasini baholash uchun faol nevrologik matritsa.",
    "tool_apgar_title": "APGAR shkalasi", "tool_apgar_desc": "Tug'ilgandan keyin 1 va 5 daqiqalarda chaqaloqning yashovchanligini tezkor baholash.",
    "about_manifesto": "Klinik manifest", "about_title": "O'rtasidagi ko'prik", "about_highlight": "Darslik va Palata.", "about_genesis": "Loyiha tarixi", "about_student": "Talaba tomonidan yaratilgan", "about_matrix": "Ko'p tilli matritsa", "about_accuracy": "Murosasiz aniqlik", "about_access": "Foydalanish imkoniyati", "about_future": "WardCalc kelajagi",
    "about_p1": "WardCalc fundamental klinik haqiqatdan kelib chiqqan: inson miyasi diagnostik fikrlash uchun ajoyib dvigatel, ammo formulalarni eslab qolish uchun juda nuqsonli qattiq diskdir.",
    "about_p2": "Auditoriyadan shifoxona palatasiga o'tish tibbiy ta'limdagi eng qiyin jarayonlardan biridir. Vaqt eng qimmatli valyutaga aylanadi. O'tkir holatlarda — GCS ni hisoblash yoki APGAR shkalasini baholash bo'ladimi — xotiraga shubha qilishga vaqt yo'q. Tibbiyot xodimlariga zudlik bilan, dalillarga asoslangan ma'lumotlar kerak.",
    "about_p3": "WardCalc xuddi shunday palatalarda ishlaydigan bitiruvchi tibbiyot talabasi tomonidan ehtiyotkorlik bilan ishlab chiqilgan klinik vositadir. Har bir piksel ortiqcha narsalardan tozalangan. Yuklanish ekranlari, majburiy kirishlar va tartibsiz menyular yo'q. Faqat yuqori stressli muhitlar uchun optimallashtirilgan sof, tezkor klinik foyda.",
    "about_p4": "Sog'liqni saqlash tabiatan globaldir. WardCalc ingliz, nemis, rus va o'zbek tillarini qo'llab-quvvatlaydigan uzluksiz ko'p tilli matritsa bilan qurilgan birinchi klinik katalogdir. Bu shifokorlarga favqulodda vaziyatlarda o'z ona tilida ballarni hisoblash imkonini beradi, shuningdek Fachsprachprüfung (FSP) kabi imtihonlar uchun o'quv qo'llanmasi sifatida xizmat qiladi.",
    "about_p5": "Tibbiy dasturiy ta'minotda hisoblash xatosi bu bemor xavfsizligiga tahdiddir. WardCalc-ga kiritilgan har bir protokol qat'iy ravishda tibbiy ko'rsatmalarga asoslanadi. Bizning kalkulyatorlarimiz shunchaki raqam bermaydi; ular bemor yotog'ida qaror qabul qilish uchun zarur bo'lgan klinik talqinni taqdim etadi.",
    "about_p6": "Bemorlarning o'limiga bevosita ta'sir ko'rsatadigan vositalar geografik va iqtisodiy tafovutlar bilan cheklanmasligi kerak deb hisoblaymiz. Resurslari cheklangan sharoitda ishlaydigan yosh shifokor xususiy shifoxonadagi mutaxassis kabi yordamga loyiqdir. Kalkulyatorlardan foydalanish 100% bepul bo'lib qoladi."
};
